const data = [
  {
    key: 1,
    label: "John Smith",
    value: "John Smith",
    gender: "Male",
    health_issue: "None",
    weight_kg: 75,
    height_cm: 180,
    calories_requirement: 2200,
    age: 35,
  },
  {
    key: 2,
    label: "Jane Doe",
    value: "Jane Doe",
    gender: "Female",
    health_issue: "Hypertension",
    weight_kg: 65,
    height_cm: 165,
    calories_requirement: 1800,
    age: 45,
  },
  {
    key: 3,
    label: "Michael Johnson",
    value: "Michael Johnson",
    gender: "Male",
    health_issue: "Diabetes",
    weight_kg: 85,
    height_cm: 175,
    calories_requirement: 2000,
    age: 50,
  },
  {
    key: 4,
    label: "Emily Wilson",
    value: "Emily Wilson",
    gender: "Female",
    health_issue: "Obesity",
    weight_kg: 95,
    height_cm: 160,
    calories_requirement: 1600,
    age: 55,
  },
  {
    key: 5,
    label: "David Brown",
    value: "David Brown",
    gender: "Male",
    health_issue: "Heart Disease",
    weight_kg: 80,
    height_cm: 170,
    calories_requirement: 1900,
    age: 40,
  },
  {
    key: 6,
    label: "Emma Martinez",
    value: "Emma Martinez",
    gender: "Female",
    health_issue: "Thyroid Disorder",
    weight_kg: 70,
    height_cm: 155,
    calories_requirement: 1700,
    age: 30,
  },
  {
    key: 7,
    label: "James Garcia",
    value: "James Garcia",
    gender: "Male",
    health_issue: "None",
    weight_kg: 90,
    height_cm: 185,
    calories_requirement: 2100,
    age: 60,
  },
  {
    key: 8,
    label: "Olivia Harris",
    value: "Olivia Harris",
    gender: "Female",
    health_issue: "Anemia",
    weight_kg: 55,
    height_cm: 150,
    calories_requirement: 1500,
    age: 25,
  },
  {
    key: 9,
    label: "William Taylor",
    value: "William Taylor",
    gender: "Male",
    health_issue: "None",
    weight_kg: 70,
    height_cm: 175,
    calories_requirement: 1950,
    age: 28,
  },
  {
    key: 10,
    label: "Sophia Lopez",
    value: "Sophia Lopez",
    gender: "Female",
    health_issue: "Osteoporosis",
    weight_kg: 65,
    height_cm: 160,
    calories_requirement: 1800,
    age: 42,
  },
];

export default data;
